#Projekat 1 - nadgledano ucenje

## Sadrzaj:
* [Ucitavanje podataka](#data_loading)
* [Priprema podataka](#data_cleaning)
  * [Provera nedostajucih vrednosti](#missing_values)
   * [Provera duplikata](#duplicate_values)

In [2]:
import pandas as pd

##Ucitavanje podataka <a name="data_loading" class="anchor" id="data_loading"></a>

Ucitavanje dataseta [Greenhouse Plant Growth Metrics](https://www.kaggle.com/datasets/adilshamim8/greenhouse-plant-growth-metrics/data)

In [41]:
dataframe=pd.read_csv('/Greenhouse_Plant_Growth_Metrics.csv')
dataframe.head()

,Random,ACHP,PHR,AWWGV,ALAP,ANPL,ARD,ADWR,PDMVG,ARL,AWWR,ADWV,PDMRG,Class
0,R1,34.533468,54.566983,1.147449,1284.229549,4.999713,16.274918,1.706810,18.399982,19.739037,2.949240,0.209251,57.633906,SA
1,R1,34.489028,54.567692,1.149530,1284.247744,5.024259,16.269452,1.700930,18.398289,19.758836,2.943137,0.216154,57.633697,SA
2,R2,33.100405,67.067344,1.104647,1009.208996,5.007652,15.980760,1.185391,19.398789,20.840822,2.861635,0.200113,41.289875,SA
3,R1,34.498319,54.559049,1.137759,1284.227623,4.991501,16.276710,1.716396,18.413613,19.736098,2.946784,0.223092,57.645661,SA
4,R3,36.297008,45.588894,1.363205,981.470310,4.003682,16.979894,0.777428,31.423772,17.331894,2.766242,0.424172,27.898619,SA

In [42]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Random  30000 non-null  object
 1   ACHP    30000 non-null  float64
 2   PHR     30000 non-null  float64
 3   AWWGV   30000 non-null  float64
 4   ALAP    30000 non-null  float64
 5   ANPL    30000 non-null  float64
 6   ARD     30000 non-null  float64
 7   ADWR    30000 non-null  float64
 8   PDMVG   30000 non-null  float64
 9   ARL     30000 non-null  float64
 10  AWWR    30000 non-null  float64
 11  ADWV    30000 non-null  float64
 12  PDMRG   30000 non-null  float64
 13  Class   30000 non-null  object
dtypes: float64(12), object(2)
memory usage: 3.2+ MB

Dataset sadrzi 30000 redova i 14 karakteristika.<br>
Random - nasumicna kategorija<br>
ACHP<br>
PHR<br>
AWWGV<br>
ALAP<br>
ANPL<br>
ARD<br>
ADWR<br>
PDMVG<br>
ARL<br>
AWWR<br>
ADWV<br>
PDMRG<br>
Class - oznaka ekperimentalne grupe

##Priprema podataka<a class="anchor" id="data_cleaning" name ="data_cleaning"></a>

###Provera nedostajucih vrednosti <a class="anchor" id="missing_values" name ="missing_values"></a>

In [47]:
dataframe.isnull().sum()

Random    0
ACHP      0
PHR       0
AWWGV     0
ALAP      0
ANPL      0
ARD       0
ADWR      0
PDMVG     0
ARL       0
AWWR      0
ADWV      0
PDMRG     0
Class     0
dtype: int64

U datasetu ne postoje nedostajuce vrednosti

In [32]:
dataframe['Class'].value_counts()

Class
SA    5000
SB    5000
SC    5000
TA    5000
TB    5000
TC    5000
Name: count, dtype: int64

In [28]:
dataframe['Random'].value_counts()

Random
R1    10045
R3     9996
R2     9959
Name: count, dtype: int64

###Provera duplikata<a class="anchor" id="duplicate_values" name ="duplicate_values"></a>

In [49]:
dataframe.duplicated().sum()

np.int64(0)